name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log In to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yishakkibru
          password: ${{ secrets.DOCKERHUB_PASSWORD  }}
      - name: Extract Metadata for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: yishakkibru/fractage
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
